let cars = [
  { car_Name: "GMC", color: "Puce", model: 2008 },
  { car_Name: "Dodge", color: "Green", model: 1996 },
  { car_Name: "Ford", color: "Aquamarine", model: 1965 },
  { car_Name: "Toyota", color: "Mauv", model: 2011 },
  { car_Name: "Pontiac", color: "Aquamarine", model: 2005 },
  { car_Name: "Chevrolet", color: "Maroon", model: 1994 },
  { car_Name: "Mercury", color: "Teal", model: 1994 },
  { car_Name: "Ferrari", color: "Blue", model: 2008 },
  { car_Name: "Volkswagen", color: "Crimson", model: 1990 },
  { car_Name: "Subaru", color: "Goldenrod", model: 2000 },
  { car_Name: "Ford", color: "Crimson", model: 1991 },
  { car_Name: "Chevrolet", color: "Violet", model: 1991 },
  { car_Name: "Subaru", color: "Mauv", model: 1999 },
  { car_Name: "Mitsubishi", color: "Aquamarine", model: 2000 },
  { car_Name: "Mercedes-Benz", color: "Crimson", model: 2012 },
  { car_Name: "Mitsubishi", color: "Maroon", model: 1988 },
  { car_Name: "GMC", color: "Yellow", model: 2012 },
  { car_Name: "Isuzu", color: "Red", model: 1996 },
  { car_Name: "Cadillac", color: "Puce", model: 2000 },
  { car_Name: "Dodge", color: "Orange", model: 1999 },
  { car_Name: "Chevrolet", color: "Violet", model: 2008 },
  { car_Name: "Hyundai", color: "Puce", model: 2013 },
  { car_Name: "Toyota", color: "Orange", model: 2009 },
  { car_Name: "Ford", color: "Turquoise", model: 1995 },
  { car_Name: "Dodge", color: "Turquoise", model: 1997 },
  { car_Name: "Buick", color: "Aquamarine", model: 1991 },
  { car_Name: "Ford", color: "Puce", model: 2000 },
  { car_Name: "Land Rover", color: "Goldenrod", model: 2009 },
  { car_Name: "BMW", color: "Puce", model: 2008 },
  { car_Name: "Isuzu", color: "Goldenrod", model: 1997 },
  { car_Name: "Isuzu", color: "Maroon", model: 1998 },
  { car_Name: "Nissan", color: "Crimson", model: 2007 },
  { car_Name: "Suzuki", color: "Turquoise", model: 1990 },
  { car_Name: "Chrysler", color: "Khaki", model: 2003 },
  { car_Name: "Pontiac", color: "Mauv", model: 1967 },
  { car_Name: "Nissan", color: "Goldenrod", model: 2003 },
  { car_Name: "Acura", color: "Maroon", model: 2008 },
  { car_Name: "Mazda", color: "Puce", model: 1984 },
  { car_Name: "Dodge", color: "Mauv", model: 1992 },
  { car_Name: "Ford", color: "Yellow", model: 1987 },
  { car_Name: "Pontiac", color: "Green", model: 1996 },
  { car_Name: "Suzuki", color: "Puce", model: 2008 },
  { car_Name: "Lexus", color: "Pink", model: 1997 },
  { car_Name: "Ford", color: "Pink", model: 1980 },
  { car_Name: "Volkswagen", color: "Blue", model: 2009 },
  { car_Name: "GMC", color: "Crimson", model: 1996 },
  { car_Name: "Porsche", color: "Pink", model: 1990 },
  { car_Name: "Mazda", color: "Khaki", model: 2006 },
  { car_Name: "Pontiac", color: "Yellow", model: 2001 },
  { car_Name: "Volkswagen", color: "Goldenrod", model: 1986 },
  { car_Name: "Audi", color: "Yellow", model: 1985 },
  { car_Name: "Mazda", color: "Blue", model: 2003 },
  { car_Name: "Saab", color: "Violet", model: 2000 },
  { car_Name: "Jeep", color: "Maroon", model: 2001 },
  { car_Name: "Mercedes-Benz", color: "Turquoise", model: 2003 },
  { car_Name: "GMC", color: "Violet", model: 2008 },
  { car_Name: "Toyota", color: "Maroon", model: 1992 },
  { car_Name: "Chrysler", color: "Indigo", model: 2009 },
  { car_Name: "Hummer", color: "Purple", model: 2009 },
  { car_Name: "Cadillac", color: "Pink", model: 2006 },
  { car_Name: "Kia", color: "Yellow", model: 2011 },
  { car_Name: "Ford", color: "Goldenrod", model: 2003 },
  { car_Name: "Ford", color: "Maroon", model: 1994 },
  { car_Name: "Chevrolet", color: "Crimson", model: 2006 },
  { car_Name: "Pontiac", color: "Yellow", model: 1991 },
  { car_Name: "GMC", color: "Turquoise", model: 2006 },
  { car_Name: "Pontiac", color: "Aquamarine", model: 1966 },
  { car_Name: "Ford", color: "Orange", model: 2007 },
  { car_Name: "Buick", color: "Puce", model: 2001 },
  { car_Name: "Plymouth", color: "Mauv", model: 1996 },
  { car_Name: "Ford", color: "Indigo", model: 1986 },
  { car_Name: "Ford", color: "Yellow", model: 2011 },
  { car_Name: "GMC", color: "Turquoise", model: 1999 },
  { car_Name: "Jensen", color: "Blue", model: 1966 },
  { car_Name: "Chevrolet", color: "Purple", model: 2010 },
  { car_Name: "Dodge", color: "Crimson", model: 1993 },
  { car_Name: "Maserati", color: "Violet", model: 2012 },
  { car_Name: "Pontiac", color: "Fuscia", model: 1992 },
  { car_Name: "Chevrolet", color: "Violet", model: 2007 },
  { car_Name: "Ford", color: "Mauv", model: 2005 },
  { car_Name: "Hummer", color: "Blue", model: 1994 },
  { car_Name: "BMW", color: "Maroon", model: 2005 },
  { car_Name: "BMW", color: "Mauv", model: 2008 },
  { car_Name: "Chevrolet", color: "Yellow", model: 1962 },
  { car_Name: "Toyota", color: "Mauv", model: 1993 },
  { car_Name: "Subaru", color: "Teal", model: 1997 },
  { car_Name: "Audi", color: "Indigo", model: 2012 },
  { car_Name: "Mercedes-Benz", color: "Indigo", model: 2012 },
  { car_Name: "Dodge", color: "Green", model: 1993 },
  { car_Name: "Jeep", color: "Indigo", model: 2008 },
  { car_Name: "Chevrolet", color: "Maroon", model: 1969 },
  { car_Name: "Chevrolet", color: "Goldenrod", model: 2009 },
  { car_Name: "Toyota", color: "Fuscia", model: 1994 },
  { car_Name: "Lexus", color: "Turquoise", model: 1998 },
  { car_Name: "Ford", color: "Orange", model: 1993 },
  { car_Name: "Infiniti", color: "Orange", model: 1994 },
  { car_Name: "Lexus", color: "Aquamarine", model: 2001 },
  { car_Name: "Mercury", color: "Khaki", model: 1986 },
  { car_Name: "Porsche", color: "Aquamarine", model: 1995 },
  { car_Name: "GMC", color: "Khaki", model: 2009 },
];

for (car of cars) {
  if (car.car_Name == "GMC" || (car.color == "Yellow" && car.model == 2011)) {
    console.log(car);
  }
}
let arr = [1, 2, 3, {}, "HEllo"];
for (a of arr) {
  console.log(a);
}
